version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Build Docker image
          command: |
            docker build -t tilak717/todo-cicd:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push tilak717/todo-cicd:$CIRCLE_SHA1
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: lachlanevenson/k8s-kubectl:latest
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Create .kube directory
          command: mkdir -p /home/circleci/.kube
      - run:
          name: Set up kubectl config
          command: |
            echo $KUBECONFIG_DATA | base64 -d > /home/circleci/.kube/config
      - run:
          name: Check Kubernetes context
          command: kubectl config current-context
      - run:
          name: Update Kubernetes deployment with the new image
          command: |
            kubectl set image deployment/todo-cicd todo-cicd=tilak717/todo-cicd:$CIRCLE_SHA1
            kubectl rollout status deployment/todo-cicd




workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
