version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build the React app
          command: npm run build

      - run:
          name: Build Docker image
          command: docker build -t tilak717/todo-cicd:1 .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push tilak717/todo-cicd:1

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Set up SSH for EC2
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts

      - run:
          name: Copy Kubernetes Config Files to EC2
          command: |
            scp -i ~/.ssh/id_rsa deployment.yaml service.yaml ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/

      - run:
          name: Deploy to Kubernetes on EC2
          command: |
            ssh -i ~/.ssh/id_rsa ubuntu@$EC2_PUBLIC_IP 'kubectl apply -f /home/ubuntu/deployment.yaml && kubectl apply -f /home/ubuntu/service.yaml'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
