version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Build Docker image
          command: |
            docker build -t tilak717/todo-cicd:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push tilak717/todo-cicd:$CIRCLE_SHA1

  deploy:
    executor: docker-executor
    steps:
      - run:
          name: Setup AWS CLI
          command: |
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Deploy to Kubernetes
          command: |
            aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
            kubectl apply -f k8s/deployment.yml
            kubectl apply -f k8s/service.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build