version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      # - run:
      #     name: Run tests
      #     command: npm test
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/todo-cicd:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/todo-cicd:$CIRCLE_SHA1

  deploy:
    executor: docker-executor
    steps:
      - checkout  # Make sure this step is present
      - run:
          name: Setup AWS CLI
          command: |
            pip install awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: Debug Path
          command: |
            echo "Current directory: $(pwd)"
            echo "Files:"
            ls -al
      - run:
          name: Deploy to Kubernetes
          command: |
            aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
            kubectl apply -f deployment.yml --validate=false
            kubectl apply -f service.yml --validate=false

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
